# Название сайта
title: VCI-BOT

# Описание
description: >
  ИИ-бот для Steam Chat на Python,
  использующий локальные нейросети через Ollama.

# Тема GitHub Pages
theme: jekyll-theme-hacker

# Настройки GitHub Pages
markdown: kramdown
plugins:
  - jekyll-seo-tag

# Настройки сайта
show_downloads: true
github:
  is_project_page: true
